class Translation {

  // field name for Firestore documents
  static const COLLECTION = 'translations';
  static const IMAGE_FOLDER = 'translationPictures';
  static const PROFILE_FOLDER = 'profilePictures'; // For storing user profile pictures
  static const TITLE = 'title';
  static const TEXT = 'orgtext';
  static const CREATED_BY = 'createdBy';
  static const PHOTO_URL = 'photoURL';
  static const PHOTO_PATH = 'photoPath';
  static const UPDATED_AT = 'updatedAt';
  static const SHARED_WITH = 'sharedWith';
 // static const IMAGE_LABELS = 'imageLabels';
  static const MIN_CONFIDENCE = 0.7;

  String docId;  //Firestore doc id
  String createdBy;
  String title;
  String orgtext;
  String photoPath; //Firebase Storage; image file name
  String photoURL;  // Firebase Storage; image URL for internet access
  DateTime updatedAt; // created or revised time
  List<dynamic> sharedWith; // list of emails
  //List<dynamic> imageLabels; // image labels generated by ML

  Translation({
    this.docId,
    this.createdBy,
    this.title,
    this.orgtext,
    this.photoPath,
    this.photoURL,
    this.updatedAt,
    this.sharedWith,
  //  this.imageLabels,
  }) {
    this.sharedWith ??= [];
   // this.imageLabels ??=[];
  }

  // convert Dart object to Firestore document
  Map<String, dynamic> serialize() {
    return <String,dynamic> {
      TITLE: title,
      CREATED_BY: createdBy,
      TEXT: orgtext,
      PHOTO_PATH: photoPath,
      PHOTO_URL: photoURL,
      UPDATED_AT: updatedAt,
      SHARED_WITH: sharedWith,
    //  IMAGE_LABELS: imageLabels,
    };
  }

  // convert Firestore doc to Dart object
  static Translation deserialize(Map<String, dynamic> data,String docId){
    return Translation(
      docId: docId,
      createdBy: data[Translation.CREATED_BY],
      title: data[Translation.TITLE],
      orgtext: data[Translation.TEXT],
      photoPath: data[Translation.PHOTO_PATH],
      photoURL: data[Translation.PHOTO_URL],
      sharedWith: data[Translation.SHARED_WITH],
    //  imageLabels: data[PhotoMemo.IMAGE_LABELS],
      updatedAt: data[Translation.UPDATED_AT] != null ?
        DateTime.fromMillisecondsSinceEpoch(data[Translation.UPDATED_AT].millisecondsSinceEpoch) : null,
    );
  }

  @override
  String toString() {
    return '$docId $createdBy $title $orgtext \n $photoURL';
  }
}